/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Cosas.Arbol;
import Cosas.Flores;
import Personajes.Ave;
import Personajes.Mariposa;
import java.awt.Graphics;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author arles96
 */
public class Lienzo extends javax.swing.JPanel {

    //Atributos
    private ArrayList<Ave> aves = new ArrayList();
    private ArrayList<Arbol> arboles = new ArrayList();
    private ArrayList<Flores> flores = new ArrayList();
    private Mariposa mariposa;
    
    
    //Constructor
    
    public Lienzo() {
        initComponents();
        configuraciones();
    }
    
    //Metodos de admisnitracion
    
    private void configuraciones(){
        /*try {
            BackgroundBorder border = new 
                BackgroundBorder(ImageIO.read(getClass().getResource("../img/paisaje.jpeg")));
            this.setBorder(border);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }*/
    }
    
    @Override
    public void paint (Graphics g){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
